###
GET localhost:8080/api/users

###
GET localhost:8080/api/people

###
GET localhost:8080/api/short_urls

###
GET localhost:8080/api/friends

###
POST localhost:8080/api/friends
Content-Type: application/json

{}

###
POST localhost:8080/api/friends
Content-Type: application/json

{
  "first-name": "Arturo",
  "last-name": "López",
  "age": 38,
  "address": {
    "street": "Residencial One",
    "city": "Cancún"
  },
  "people": [{
    "name": "Elon Musk"
  },{
    "name": "Steve Jobs"
  }]
}

###
GET localhost:8080/api/friends/1

###
PUT localhost:8080/api/friends
Content-Type: application/json

{
  "id": 1,
  "first-name": "Arturo",
  "last-name": "López Gómez",
  "age": 38
}

###
DELETE localhost:8080/api/friends/1

###
GET localhost:8080/api/friends/search?first=Arturo&last=Gómez

###
GET localhost:8080/api/friends/search?first=Arturo

###
GET localhost:8080/api/friends/search?last=López

###
GET localhost:8080/api/friends/search

###
GET localhost:8080/people

###
GET localhost:8080/api/people/8/friend
