###
GET localhost:8080/api/users

###
GET localhost:8080/api/people

###
GET localhost:8080/api/short_urls

###
GET localhost:8080/api/friends

###
POST localhost:8080/api/friends
Content-Type: application/json

{
  "firstName": "Arturo",
  "lastName": "López"
}

###
GET localhost:8080/api/friends/1

###
PUT localhost:8080/api/friends
Content-Type: application/json

{
  "id": 2,
  "firstName": "Arturo",
  "lastName": "López Gómez"
}

###
DELETE localhost:8080/api/friends/1

###
GET localhost:8080/api/friends/search?first=Arturo&last=Gómez

###
GET localhost:8080/api/friends/search?first=Arturo

###
GET localhost:8080/api/friends/search?last=López

###
GET localhost:8080/api/friends/search

###
GET localhost:8080/people
