from urllib.parse import urlparse
parsed = urlparse('https://arthurolg.com/about/?param1=1&param2=12#/example_fragment')
print('scheme  :', parsed.scheme)
print('netloc  :', parsed.netloc)
print('path    :', parsed.path)
print('params  :', parsed.params)
print('query   :', parsed.query)
print('fragment:', parsed.fragment)
print('username:', parsed.username)
print('password:', parsed.password)
print('hostname:', parsed.hostname, '(netloc in lower case)')
print('port    :', parsed.port)
